name: Build and Release

on:
  push:
    tags:
      - '*'

env:
  DOTNET_VERSION: '7.0.100'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            runtime-id: win-x64
          - os: ubuntu-latest
            runtime-id: linux-x64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: dotnet build --configuration Release --runtime ${{ matrix.runtime-id }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - ...
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/Release/net7.0/${{ matrix.runtime-id }}/PiwoConverter.Console.dll
          asset_name: PiwoConverter.Console.dll
          asset_content_type: application/octet-stream
